# Generated by Django 2.0.10 on 2019-01-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
