# Generated by Django 2.0.10 on 2019-01-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190111_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
    ]
