# Generated by Django 2.0.10 on 2019-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190111_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='quartier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='ville',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='quartier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='ville',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
