# Generated by Django 2.0.10 on 2019-01-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190112_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigneaclasse',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='api.Enseignant'),
        ),
    ]
