# Generated by Django 2.0.10 on 2019-01-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190113_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('Terminale', 'Terminale'), ('Première', 'Première'), ('Terminale A', 'Terminale A'), ('Terminale C', 'Terminale C'), ('Terminale D', 'Terminale D'), ('Première A', 'Première A'), ('Première C', 'Première C'), ('Première D', 'Première D'), ('Seconde A', 'Seconde A'), ('Seconde C', 'Seconde C'), ('Seconde', 'Seconde'), ('Troisième', 'Troisième'), ('Quatrième', 'Quatrième'), ('Cinquième', 'Cinquième'), ('Sixième', 'Sixième')], default='Sixième', max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Terminale', 'Terminale'), ('Première', 'Première'), ('Terminale A', 'Terminale A'), ('Terminale C', 'Terminale C'), ('Terminale D', 'Terminale D'), ('Première A', 'Première A'), ('Première C', 'Première C'), ('Première D', 'Première D'), ('Seconde A', 'Seconde A'), ('Seconde C', 'Seconde C'), ('Seconde', 'Seconde'), ('Troisième', 'Troisième'), ('Quatrième', 'Quatrième'), ('Cinquième', 'Cinquième'), ('Sixième', 'Sixième')], max_length=50, null=True),
        ),
    ]
