# Generated by Django 2.0.10 on 2019-01-13 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190113_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='prix',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
