# Generated by Django 2.0.10 on 2019-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190113_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
