# Generated by Django 2.0.10 on 2019-01-19 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quizz_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='duree',
            field=models.CharField(default='time', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='nombreEssai',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='note',
            field=models.IntegerField(default=101, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)]),
        ),
    ]
