# Generated by Django 2.0.10 on 2019-01-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190119_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, default='qcm', max_length=50, null=True)),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ChapitreClasse')),
            ],
        ),
    ]
