# Generated by Django 2.0.10 on 2019-01-25 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190120_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='numero',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)]),
        ),
    ]
