# Generated by Django 2.0.10 on 2019-01-27 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionSchema',
            fields=[
                ('idPropositionSchema', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('annotation', models.CharField(blank=True, default='Annontation', max_length=100, null=True)),
                ('reponse', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Question')),
            ],
        ),
    ]
